# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - rapportService

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_663fe7508be14951891c3cedc4eb4124 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a067d524946f41f98bd190e0555b59da }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_663fe7508be14951891c3cedc4eb4124 }}/rapport_service:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rapportService'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1073959dffb3456296844e702a6ca404 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_663fe7508be14951891c3cedc4eb4124 }}/rapport_service:${{ github.sha }}'

    - name: Add environment variable to Azure App Service
      uses: Azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az webapp config appsettings set \
            --name rapportService \
            --resource-group Exam_Resources \
            --settings LEJEAFTALE_SERVICE_URL=http://lejeaftaleservice-cqa6f7hgc8b0f6ek.northeurope-01.azurewebsites.net
